#!/bin/sh

# Rename the BDE-style "package" in which the code in this repository is
# defined, and place the modified files in a specified directory.
#
# The code currently is in the "package" package. The idea is that you run
#
#     $ ./rename-package mypkg ~/code/mypkg
#
# and this script will rewrite the C++ code as if it were in the "mypkg"
# package, and then copy the rewritten code into the "~/code/mypkg" directory.

if [ "$#" -ne 2 ]; then
    >&2 echo "Usage: $0 <package-name> <output-directory>"
    exit 1
fi

newname=$1
outdir=$2

for file in $(ls package_*); do
    out=$outdir/$newname${file#package}
    upper=$(echo $newname | tr [a-z] [A-Z])

    sed "s/#ifndef INCLUDED_PACKAGE/#ifndef INCLUDED_$upper/" $file | \
    sed "s/#define INCLUDED_PACKAGE/#ifndef INCLUDED_$upper/" | \
    sed "s/#include <package/#include <$newname/" | \
    sed "s/namespace package /namespace $newname /" > $out

done
